site_name: Open Source Analog and Mixed-Signal Design
site_description: Introduction to Open Source Analog and Mixed-Signal (AMS) Design
site_author: Cedric Hirschi
site_url: https://CedricHirschi.github.io/osams-docs/
repo_name: osams-docs
repo_url: https://github.com/CedricHirschi/osams-docs/

nav:
  - Home: index.md
  - Setup:
      - IIC-OSIC-TOOLS Image: setup/container.md
      - OSEDA: setup/oseda.md
      - XSCHEM: setup/xschem.md
  - XSCHEM:
      - PDK Examples: xschem/pdk_examples.md
      - Creating a New Design: xschem/creating_design.md
      - Analysis in Python: xschem/python.md
  - Cosimulation:
      - Introduction: cosimulation/intro.md
      - Creating a Mixed-Signal Simulation: cosimulation/design.md
      - Bridges: cosimulation/bridges.md

copyright: Copyright &copy; 2025 <a href="mailto:cehirschi@student.ethz.ch">Cedric Hirschi</a>

theme:
  name: material

  font:
    text: Roboto Flex
    code: Roboto Mono

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: black
      accent: amber
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: black
      accent: amber

  icon:
    # logo: material/black-mesa
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.prune
    - toc.follow
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips

plugins:
  - search
  - social
  - glightbox
  - exporter:
      formats:
        pdf:
          enabled: !ENV [MKDOCS_EXPORTER_PDF, false]
          concurrency: 8
          aggregator:
            enabled: true
            output: /workspaces/ngspice_cosim_inv/instructions/site/site.pdf
            covers: all
  # - privacy

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.blocks.caption
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# Include static files by adding them to nav or using hooks
hooks:
  - hooks.py
